version: '3.8'

services:
  srgan-rust:
    build:
      context: .
      dockerfile: Dockerfile
    image: srgan-rust:latest
    container_name: srgan-rust
    volumes:
      # Mount current directory as workspace
      - ./:/workspace
    working_dir: /workspace
    # Override entrypoint for interactive use
    entrypoint: ["/usr/local/bin/srgan-rust"]
    # Default command - can be overridden
    command: ["--help"]
    
  # Service for batch processing
  srgan-batch:
    image: srgan-rust:latest
    volumes:
      - ./input:/workspace/input:ro
      - ./output:/workspace/output
    working_dir: /workspace
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "for file in input/*.{jpg,png,jpeg}; do
        if [ -f \"$$file\" ]; then
          filename=$$(basename \"$$file\")
          echo \"Processing $$filename...\"
          srgan-rust \"$$file\" \"output/$${filename%.*}_4x.png\"
        fi
      done"
      
  # Service for training
  srgan-train:
    image: srgan-rust:latest
    volumes:
      - ./training_data:/workspace/training_data:ro
      - ./models:/workspace/models
    working_dir: /workspace
    entrypoint: ["/usr/local/bin/srgan-rust"]
    command: ["train", "-r", "/workspace/training_data", "/workspace/models/custom_model.rsr"]