apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: srgan-models-pvc
  namespace: srgan
  labels:
    app: srgan-api
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
