apiVersion: v1
kind: Service
metadata:
  name: srgan-api
  namespace: srgan
  labels:
    app: srgan-api
spec:
  type: ClusterIP
  selector:
    app: srgan-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
