pub mod batch;
pub mod benchmark;
pub mod downscale;
pub mod generate_config;
pub mod psnr;
pub mod quantise;
pub mod set_width;
pub mod train;
pub mod train_prescaled;
pub mod upscale;

pub use self::batch::batch_upscale;
pub use self::benchmark::benchmark;
pub use self::downscale::downscale;
pub use self::generate_config::{generate_config, train_with_config};
pub use self::psnr::psnr;
pub use self::quantise::quantise;
pub use self::set_width::set_width;
pub use self::train::train;
pub use self::train_prescaled::train_prescaled;
pub use self::upscale::upscale;
